- server/src/models/account.js
- server/src/models/income.js
#11 sequelize 기반 테이블 생성
- sequelize로 account 모델을 생성
- accountbook, income, expenditure과의 관계 설정
- sequelize로 income 모델을 생성
- income_category, accountbook, account와의 관계 설정
> sequelize를 활용하여 income, account 모델 생성 및 관계 설정

- client/package-lock.json
- client/package.json
- client/tsconfig.json
- package-lock.json
npm run start가 동작하지 않음
- babel-loader 삭제
- babel-core 삭제 ( 둘 모두 CRA 내부에 있는 패키지입니다. )
- typescript를 4.0.5 버전으로 명시
no overload matched (styled-components)
> fix : typescript 버전 호환 문제

- client/src/components/graph/Circle.tsx
- client/src/components/graph/PieGraph.stories.tsx
- client/src/components/graph/PieGraph.tsx
- CircleSVG.tsx 파일에서 발생하는 타입 오류를 명시적 타입을 주는 방법으로 수정해서 해결했습니다.
- storiesbook의 컴포넌트에 모두 타입을 지정해줬습니다.
> storiesbook에 타입 지정, 타입 오류로 인해서 발생하는 에러 수정

- client/src/components/color-picker/ColorPicker.stories.tsx
- client/src/components/color-picker/ColorPicker.tsx
[공통 컴포넌트] color picker 페인트통&팔레트 컴포넌트 #72 
- 영근님의 리뷰를 반영하여 렌더링이 한번만 일어나도록 수정하였습니다.
>
>와 새벽에 진짜 수고 많으셨습니다~~~
>다름이 아니라 이 부분이 조금 걸려요. props-> state값을 매핑했잖아요? 만약 InputColor 값이 변경되면 onChange 이벤트에 의해서
>setInptuColor state가 변한뒤 (1) ColorPicker 컴포넌트 렌더링, 이 수행될것 같아요. 리 렌더링후 useEffect에 의해서 부모의 color가 변경되면 (2) 부모 컴포넌트 리렌더링 이 될것 같아요. color props 값이 변경되기 때문에 (3) ColorPicker 컴포넌트가 리 렌더링이 될것 같아요. state를 부모에게 전부 위임하고view만 보여주는 stateless 컴포넌트로 바꾸거나 아니면 색 정보를 자신의 state로 관리하는 컴포넌트가 되야할것 같아요.
>
>P.S props를 state에 다시 매핑하는것은 안티패턴이라고 해요
>https://www.reddit.com/r/javascript/comments/5t73cd/why_is_props_to_state_an_antipattern_in_reactjs/
> colorPicker 동작방식 수정

- client/src/components/home-button/HomeButton.stories.tsx
- client/src/components/plus-button/PlusButton.stories.tsx
- client/src/components/small-accountbook-item/SmallAccountbookItem.stories.tsx
- client/src/components/small-accountbook-item/SmallAccountbookItem.tsx
[가계부 내역 페이지] 사이드바 홈 버튼 오류 fix #54
[가계부 내역 페이지] 사이드바 가계부 버튼 오류 fix #55
[가계부 내역 페이지] 사이드바 가계부 생성 버튼 오류 fix #56
<br>
- #54 
- HomeButton 스토리 파일에서 필요한 'show' props가 없어서 생기는 문제 해결
- #55 
- SmallAccountbookItem 스토리 파일에서 필요한 'show' props가 없어서 생기는 문제 해결
- Styled => styled 로 변경
- #56 
- PlusButton 스토리 파일에서 필요한 'show' props가 없어서 생기는 문제 해결
<br>
> sidebar가 storybook에서 출력되지 않는 문제 해결

- client/src/components/common/settings-sidebar/SettingsSidebar.stories.tsx
- client/src/components/common/settings-sidebar/SettingsSidebar.tsx
- client/src/components/common/settings-sidebar/settings-sidebar-body/SettingsSidebarBody.stories.tsx
- client/src/components/common/settings-sidebar/settings-sidebar-body/SettingsSidebarBody.tsx
- client/src/components/common/settings-sidebar/settings-sidebar-header/SettingsSidebarHeader.stories.tsx
- client/src/components/common/settings-sidebar/settings-sidebar-header/SettingsSidebarHeader.tsx
close #80 [공통 컴포넌트] 좌측 사이드바 컴포넌트
- 가계부 관리 페이지 좌측 Sidebar의 Header 컴포넌트 구현
- SettingsSidebarHeader 컴포넌트는 클릭 시 이전 페이지로 이동하는 ModalBackButton과 페이지 이름인 '가계부 관리'가 포함
- SettingsSidebarHeader 컴포넌트 스토리 파일 생성
<br>
- 가계부 관리 페이지 좌측 Sidebar의 Body 컴포넌트 구현
- SettingsSidebarBody 컴포넌트는 클릭 시 해당 메뉴를 설정하는 페이지로 이동하는 SettingsSidebarMenuItem으로 구성
- SettingsSidebarBody 컴포넌트 스토리 파일 생성
- SettingsSidebarMenuItem 컴포넌트에 currentPage 속성을 추가하여 현재 페이지에 해당하는 MenuItem 텍스트를 BLUE 색상으로 표시
<br>
- 가계부 관리 페이지 좌측 Sidebar 컴포넌트 구현
- SettingsSidebarHeader와 SettingsSidebarBody 컴포넌트를 합쳐서 SettingsSidebar 컴포넌트 생성
<br>
<br>
- HeaderNavigation 컴포넌트 구현 코드 참고하여 작업
<br>
> 가계부 관리 페이지 좌측 Sidebar 컴포넌트 구현

- server/src/models/accountbook.js
- server/src/services/oauth.js
- accountbook의 gmt 속성이 string으로 되어 있던 걸 integer로 변경했습니다.
- 카카오로 OAuth 로그인할 때, 프로필 사진이 없으면 프로필 url이 undefined로 오는 것을 확인했습니다. undefined일 경우 미리 지정한 default url을 사용할 수 있도록 수정하였습니다.
> accountbook 테이블 스키마 변경, 카카오 oauth 로그인 시 프로필 사진 없을 때 버그 수정

- server/src/api/controllers/transaction.js
- server/src/api/routes/transaction.js
- server/src/services/transaction.js
close #193 수입 내역 수정 API
close #194 지출 내역 수정 API 구현
close #195 수입 내역 삭제 API 구현
close #196 지출 내역 삭제 API 구현
- 수입 내역 수정 API를 구현하였습니다.
- 지출 내역 수정 API를 구현하였습니다.
- 수입 내역 삭제 API를 구현하였습니다.
- 지출 내역 삭제 API를 구현하였습니다.
- 특정 지출/수입을 조회하는 로직이 반복되어 함수로 분리하였습니다.
- API Docs를 수정하였습니다.
> 내역 수정,삭제 API 구현

- client/src/components/common/account/Account.tsx
- client/src/components/common/add-category-button/AddCategoryButton.stories.tsx
- client/src/components/common/add-category-button/AddCategoryButton.tsx
- client/src/components/common/category/Category.tsx
- client/src/components/common/modals/form-modal-account/FormModalCreateAccount.tsx
- client/src/components/common/modals/form-modal-account/FormModalUpdateAccount.tsx
- client/src/components/common/modals/form-modal-category/FormModalCreateCategory.tsx
- client/src/components/common/modals/form-modal-category/FormModalUpdateCategory.tsx
- client/src/components/common/modals/formUtils.ts
- client/src/components/common/modals/modals.stories.tsx
- client/src/constants/color.ts
- client/src/constants/formModal.ts
- client/src/pages/settings-accounts-page/SettingsAccountsView.tsx
- client/src/pages/settings-categories-page/SettingsCategoriesView.tsx
- client/src/services/account.ts
- client/src/services/category.ts
- client/src/store/CategoryStore.tsx
- client/src/store/modal-store/CreateCategoryFormStore.tsx
- client/src/store/modal-store/ModalStore.tsx
- client/src/store/modal-store/UpdateAccountFormStore.tsx
- client/src/store/modal-store/UpdateCategoryFormStore.tsx
- client/src/types/account.ts
- client/src/types/category.ts
- server/src/api/controllers/account.js
- server/src/api/controllers/category.js
- server/src/api/routes/account.js
- server/src/api/routes/category.js
- server/src/services/account.js
- server/src/services/category.js
close #198 [가계부 관리 페이지] 결제수단 수정 API 
close #199 [가계부 관리 페이지] 지출/수입 카테고리 수정 API 
#200 [가계부 관리 페이지] 결제수단 수정/삭제 모달창 구현 
#201 [가계부 관리 페이지] 지출/수입 카테고리 수정/삭제 모달창 구현 
close #209 [가계부 관리 페이지] 결제수단 삭제 API 
close #210 [가계부 관리 페이지] 지출/수입 카테고리 삭제 API 
<br>
- 카테고리 관리 페이지
- 지출/수입 카테고리 생성 기능 FE, BE 연동 완료
- BE
- 특정한 수입/지출 카테고리를 수정하는 API 구현 및 관련 BE 로직 추가
- 특정한 수입/지출 카테고리를 삭제하는 API 구현 및 관련 BE 로직 추가
- FE
- 카테고리 수정/삭제 모달창 구현
- 결제수단 관리 페이지
- 결제수단 생성 기능 FE, BE 연동 완료
- BE
- 특정한 결제수단을 수정하는 API 구현 및 관련 BE 로직 추가
- 특정한 결제수단을 삭제하는 API 구현 및 관련 BE 로직 추가
- FE
- 결제수단 수정/삭제 모달창 구현
<br>
<br>
<br>
- BE에서 카테고리 수정/삭제 및 결제수단 수정/삭제 API는 테스트를 마쳤으나 BE, FE 연동 구현 필요
- 카테고리 및 결제수단 컴포넌트 클릭 시 해당하는 컴포넌트가 가진 데이터들이 모달창에 들어가는 로직 구현 필요
<br>
> 카테고리 수정 모달창, 결제수단 수정 모달창 구현 및 관련 BE 작업

- client/src/pages/settings-csv-page/SettingsCsvView.tsx
csv 페이지에서 더이상 사용하지 않는 모듈을 import해와서 npm start가 되지 않는 문제가 발생합니다. 제거하겠습니다.
> hotfix - 더이상 사용하지 않는 모듈 제거

- server/src/__test__/services/sms-parsing.test.js
- server/src/api/controllers/transaction.js
- server/src/api/routes/transaction.js
- server/src/services/transaction.js
close #261 [가계부 내역 페이지] 결제내역 SMS/MMS 파싱 API 구현
- 결제내역 SMS/MMS 파싱하는 함수를 구현했습니다.
- 결제내역 SMS/MMS 파싱하는 함수에 대해 테스트 파일을 생성했습니다.
- API 문서화했습니다.
아직 완벽하지는 않은 것 같습니다. 함수를 구현한 후 테스트케이스를 계속 조정해보며, 아래와 같이 쉼표 두 개 이상이 등장하는 금액이 나올 때 처리하지 못한 걸 처리했습니다. 리팩토링 기간에 여유가 된다면 테스트 케이스를 더 수집하여 성능을 향상시켜도 좋을 것 같습니다.
- 실패한 테스트케이스
- replace가 한 번 이루어지기 때문에 발생했던 문제였습니다.
- replace 함수의 첫번째 인자를 정규식으로 주어 문제를 해결했습니다.
> 결제 내역 문자 파싱 기능 BE 추가

- client/src/components/common/small-accountbook-item/SmallAccountbookItem.tsx
close #265 [가계부 내역 페이지] 사이드바에 있는 가계부에 hover했을 때 가계부 설명 출력 
<br>
- 사이드바에 있는 가계부에 hover했을 때 가계부 관련 정보 출력
- 출력창에는 해당하는 가계부 색상의 출력창이 출력된다.
- 출력창에는 해당하는 가계부 이름과 가계부 설명이 출력된다.
- 사이드바에 있는 가계부에 hover했을 때의 간단한 style 변경
<br>
<br>
- 가계부 선택 페이지 구현이 완료되면 사이드바에 유저가 가지고 있는 가계부가 출력되도록 해야 한다.
- 클릭했을 때 해당 가계부의 내역 페이지로 이동하는 로직 추가 필요
- hover했을 때 해당 가계부의 이름, 설명이 연동되는 로직 추가 필요
<br>
> 사이드바에 있는 가계부에 hover했을 때 가계부 설명 출력되는 기능 추가

- server/src/app.js
- server/src/loaders/koa.js
cors의 origin에서 사용하는 client port가 80번일 경우 아예 기재해주지 않아야 정상적으로 동작하는 것을 확인했습니다.
hotfix로 머지하겠습니다.
> cors 80번 포트일 때 문제 생겼던 부분 처리

- server/src/api/controllers/category.js
- server/src/services/account.js
- server/src/services/category.js
- API Docs를 정리하는 과정에서 카테고리 생성, 결제수단 생성 API의 응답이 created_at과 updated_at을 포함하는 것을 발견하여 이 부분을  id, name, color 속성만 보내주도록 수정하였습니다.
> 카테고리 생성, 결제수단 생성 API 수정

- server/src/api/controllers/accountbook.js
- server/src/api/routes/accountbook.js
- server/src/services/accountbook.js
close #291 가계부 생성 API 구현
- 가계부 생성 API 만들었습니다.
- 유저가 가계부 생성 시 accountbook 테이블에 가계부를 만든 후, userAccountbook 테이블에서 해당 유저와 새로 만든 테이블의 관계 레코드 하나를 만듭니다.
- 반환은 accountbook 테이블의 title까지 포함합니다.
> 가계부 생성 API 구현

- client/src/components/common/modals/form-modal-account/FormModalUpdateAccount.tsx
- client/src/components/common/modals/form-modal-category/FormModalUpdateCategory.tsx
- server/src/services/account.js
- server/src/services/category.js
close #283 [가계부 설정 페이지] 카테고리, 결제수단 중복검사 로직 버그 수정
- color만 바뀐 경우에도 완료 버튼이 활성화 되도록 수정하였습니다.
- 백엔드에서도 이름과 컬러가 모두 같은 경우에만 중복 되었다고 판단하도록 로직을 수정하였습니다.
> 카테고리, 결제수단 중복검사 로직 버그 수정

- client/src/components/common/sidebar/Sidebar.tsx
- client/src/components/common/transactions/all-transaction-container/AllTransactionContainer.tsx
- client/src/components/common/transactions/day-transaction-container/DayTransactionContainer.tsx
- client/src/pages/transaction-page/TransactionView.tsx
- client/src/store/TransactionStore.tsx
- client/src/utils/sortByRecentDate.ts
close #330 [가계부 내역 페이지] 무한스크롤 적용 
<br>
- 가계부 내역 페이지에 무한 스크롤 적용
<br>
<br>
- 모든 거래내역이 렌더링되고 스크롤을 위로 올렸다가 다시 내렸을 때 계속 items가 증가하는 부분 수정 필요 => 오류는 없으나 불필요한 이벤트 발생 최소화
- 무한스크롤 최적화를 위해 디바운싱 혹은 쓰로틀링 적용 필요 => 일정 시간동안 같은 이벤트(scroll)가 발생하지 않도록 해주는 기능
<br>
> 가계부 내역 페이지에 무한스크롤 적용

- client/src/pages/transaction-page/TransactionView.tsx
- client/src/store/TransactionStore.tsx
- 스크롤이 제일아래에 있더라도 scrollTop + clientHeight < scrollHeight 인 경우가 있어서 +1 을 해줘서 너무 민감하게 반응하지 않도록 하였습니다.
- items가 20개 이상  쌓였을 때 달을 변경하거나 필터링을 하면 items가 그대로
20개 이상으로 유지되어 20개만 렌더링하는게 아니라 items 만큼 렌더링하는
오류를 수정하였습니다.
> hotfix: 무한스크롤 버그 수정

- client/src/components/accountbook-social-page/user-item/UserItem.tsx
- client/src/components/common/header-navigation/HeaderNavigation.tsx
- client/src/components/common/modals/form-modal-filter/FormModalFilter.tsx
- client/src/components/common/modals/give-admin-modal/UserItemWithRadio.tsx
- client/src/components/common/profile-dropdown/ProfileDropdown.tsx
- client/src/components/common/profile-image/ProfileImage.tsx
- client/src/pages/transaction-page/TransactionView.tsx
- client/src/store/TransactionStore.tsx
#340 [가계부 내역 페이지] 무한스크롤 최적화 작업 
#341 [가계부 내역 페이지] 필터 모달창이 열린 상태에서 스크롤을 따라오지 못하는 오류 해결하기 
<br>
- 거래내역 페이지의 거래내역들이 모두 렌더링되고 마우스를 스크롤을 올렸다가 다시 페이지 맨 밑에 도착했을 때 items가 계속 증가하는 문제 해결
- 거래내역 필터 모달창이 스크롤을 따라 내려오지 못하는 버그 수정
- ProfileImage 사이즈 확대 및 HeaderNavigation font-size 조절
<br>
<br>
<br>
- 우리 서비스에는 굳이 디바운싱과 쓰로틀링이 필요하지 않을 것이라고 판단
- 디바운싱: 반복적으로 호출되는 함수 중 마지막 함수만 호출하는 기법
- 쓰로틀링: 마지막 함수가 호출된 후 일정 시간이 지나기 전까지 다시 호출되지 않도록 하는 기법
- 무한스크롤 최적화 결론
- 거래내역이 모두 렌더링되면 scroll eventListener를 삭제하는 방식으로 최적화 (구현 필요)
- 스크롤을 위로 올렸을 때는 페이지 가장 밑에 도달했는지 검사하는 로직이 실행되지 않도록 조건문 삽입 (구현 완료)
- 필터 모달창을 fixed로 설정하니 드롭다운이 페이지에서 잘려보이는 오류 발생 (해결 필요)
<br>
> 무한스크롤 items 늘어나는 부분 수정 및 거래내역 필터 모달창 버그 수정

- client/src/components/common/category/Category.tsx
- client/src/components/common/transactions/all-transaction-container/AllTransactionContainer.tsx
- client/src/components/common/transactions/day-transaction-container/DayTransactionContainer.tsx
- client/src/components/transaction-page/filter-option/FilterOption.tsx
- client/src/pages/settings-accountbook-page/SettingsAccountbookPage.tsx
- client/src/pages/settings-accounts-page/SettingsAccountsView.tsx
- client/src/pages/settings-categories-page/SettingsCategoriesView.tsx
- client/src/pages/settings-social-page/SettingsSocialPage.tsx
- client/src/pages/transaction-page/TransactionView.tsx
- client/src/store/AccountStore.tsx
- client/src/store/AccountbookStore.tsx
- client/src/store/CategoryStore.tsx
- client/src/store/SocialStore.tsx
- client/src/store/TransactionStore.tsx
- client/src/store/modal-store/FilterFormStore.tsx
- client/src/utils/date.ts
- client/src/utils/sortByRecentDate.ts
#338 콘솔에 나오는 mobx wargings 제거하기
- 내역페이지에서 총 내역의 개수 표시
- 상태변화를 action으로 감싸 mobx warning을 제거 (원인불명으로 몇개는 제거 못함)
- 특정 날짜의 총지출과 총수입의 합을 계산하는 로직을 좀 더 깔끔하게 리팩토링
- 필터링부분 로직 좀 더 깔끔하게 리팩토링
> 내역의 개수 표시, 각종 버그 수정, 코드 리팩토링 

- client/src/pages/transaction-page/TransactionView.tsx
- client/src/store/TransactionStore.tsx
월 바꿨을 때 무한스크롤이 동작하지 않는 오류를 해결하였습니다.
월이 바꼈을 때 lastScrollTop 값을 초기화해주었습니다.
> 월 바꿨을 때 무한스크롤 동작하지 않는 오류 해결

- client/src/store/LineChartStore.tsx
- client/src/utils/filter.ts
- client/src/utils/form/validation.ts
- server/src/services/account.js
- server/src/services/category.js
close #360 [가계부 통계 페이지] 라인차트 월변경 오류 수정
close #363 [가계부 통계 페이지] 파이차트 기타항목 계산 오류 수정
close #364 중복검사 로직 버그 수정
- 이전에 만들었던 유틸함수를 사용해 월 변경이 이상하게 되는 오류를 해결하였습니다.
- 파이차트에서 기타(remain) 항목을 계산할 때 하위 항목이 아니라 상위 항목을 계산해버리는 오류가 있어서 해당 부분을 수정하였습니다.
- 프론트에서 중복된 이름인데도 불구하고 색깔이 다른경우 완료버튼이 활성화되는 버그를 해결하였습니다.
- 백엔드에서 중복되는 이름이지만 색깔만 다른경우 수정이 허용되는 오류가 있어서 그 부분의 로직을 수정하였습니다.
> 라인차트 월변경 오류 수정, 파이차트 기타항목 계산 오류 수정, 중복검사 오류 수정

- client/src/pages/settings-accountbook-page/SettingsAccountbookPage.tsx
accountbookStore.accountbook이 undefined라서 생기는 오류 해결했습니다.
> 가계부 설정 페이지 들어갈 때 생기는 오류 해결
