- .gitignore
- server/.eslintrc.js
- server/.prettierrc.json
- server/package-lock.json
- server/package.json
백엔드 eslint, prettier 설정 #3 
server 폴더(백엔드) 에서 eslint와 prettier 설정을 하였습니다.
> 백엔드 eslint, prettier 설정

- server/src/models/expenditure.js
- server/src/models/expenditureCategory.js
- server/src/models/user.js
sequelize 기반 테이블 생성 #11
- expenditure 테이블 스키마를 작성하고, 다른 테이블과의 관계를 설정했습니다.
- expenditure_category 테이블 스키마를 작성하고, 다른 테이블과의 관계를 설정했습니다.
- user 테이블에서 잘못 기재된 객체명을 수정했습니다.
> seqeuelize 활용하여 지출 내역, 지출 카테고리 테이블 생성

- server/src/models/accountbook.js
- server/src/models/userAccountbook.js
#11 sequelize 테이블 생성
- accountbook 테이블 스키마를 작성하고 관계를 설정했습니다.
- userAccountbook 스키마를 작성하고 관계를 설정했습니다.
> #11sequelize userAccountbook,accountbook 모델 생성

- server/src/models/incomeCategory.js
- server/src/models/index.js
sequelize 기반 테이블 생성 #11
- sequelize 모델 incomeCategory를 생성하였습니다.
> sequelize income_category 모델 설정

- client/package-lock.json
- client/package.json
- client/src/components/graph/Circle.tsx
- client/src/components/graph/PieGraph.stories.tsx
- client/src/components/graph/PieGraph.tsx
- server/src/models/accountbook.js
- server/src/models/userAccountbook.js
#17 PieChart
- SVG 형식의 PieChart 생성
- PieChart Stories 생성
> PieChart 컴포넌트 생성

- server/src/config/db.js
- server/src/loaders/index.js
- server/src/loaders/mysql.js
- server/src/models/accountbook.js
- server/src/models/user.js
- server/src/models/userAccountbook.js
sequelize 기반 테이블 생성 #11
- sequelize를 활용하여 테이블을 생성할 때 제대로 관계가 설정되어 있지 않은 부분들을 수정하였습니다.
- lint 및 prettier가 적용되지 않은 파일들을 적용시켜줬습니다.
> seqeulize를 활용한 테이블 생성 코드 수정

- client/package-lock.json
- client/package.json
- client/src/App.tsx
- client/src/components/color-picker/ColorPicker.stories.tsx
- client/src/components/color-picker/ColorPicker.tsx
[공통 컴포넌트] color picker 페인트통&팔레트 컴포넌트 #72
- ColorPicker 컴포넌트를 생성하였습니다.
- html의 input 태그를 이용하면 드래그 할 때마다 상태가 계속 바껴서 렌더링이 엄청 느려지는
오류가 있어서 react-input-color를 사용하여 드래그 할 때마다 바뀌는게
아니라 클릭할 때 마다 색이 바뀌도록 하였습니다.
> ColorPicker 컴포넌트 구현

- client/.eslintrc.js
- client/.prettierrc.js
- client/package-lock.json
- client/package.json
- client/src/App.tsx
구현/수정 내용
- 타입스크립트 환경에 맞게 프론트엔드 eslint, prettier 설정을 하였습니다.
> 프론트엔드 eslint, prettier 설정

- client/src/components/color-picker/ColorPicker.stories.tsx
- client/src/components/color-picker/ColorPicker.tsx
ColorPicker 컴포넌트에서 타입오류로 인한 에러를 해결하였습니다.
> ColorPicker 타입스크립트 에러 해결

- client/src/components/graph/Circle.tsx
- client/src/components/graph/PieGraph.stories.tsx
- client/src/components/graph/PieGraph.tsx
- ReactNode 컴파일이 안되는 문제가 생겨 JSXElement로 변경했습니다.
> FIX : ReactNode -> JSXElement로 변경

- client/src/__tests__/axios.test.ts
- client/src/api/axios.ts
- server/package-lock.json
- server/package.json
- server/src/loaders/koa.js
axios instance 구현 #121
- axios instance baseURL을 구현하였습니다.
- axios instance 헤더 Bearer token 설정
- 백엔드 cors 설정
```
REACT_APP_BASE_URL=http://xxx.xxx.xxx:5000
```
> axios instance 구현, cors 설정

- client/src/App.tsx
- client/src/components/login-button/naver-login-button/NaverLoginButton.stories.tsx
- client/src/pages/transaction-page/TransactionPage.tsx
- client/src/pages/transaction-page/TransactionView.tsx
> 타입에러, 이름에러 수정

- client/src/components/login-button/kakao-login-button/KakaoLoginButton.stories.tsx
- client/src/components/login-button/kakao-login-button/LargeKakaoLoginButton.tsx
- client/src/components/login-button/kakao-login-button/SmallKakaoLoginButton.tsx
- client/src/components/login-button/naver-login-button/LargeNaverLoginButton.tsx
- client/src/components/login-button/naver-login-button/SmallNaverLoginButton.tsx
- client/src/pages/login-page/LoginPage.stories.tsx
- client/src/pages/login-page/LoginPage.tsx
- client/src/types/loginButton.ts
#27 ([로그인 페이지] 로그인 페이지 UI 구성)
- 반응형 웹 관련 리팩토링 작업 했습니다.
- 버튼 크기도 브라우저 크기에 따라 변화하게 만들었습니다.
- 폰트 크기 및 패딩, 마진 조정했습니다.
- App 컴포넌트에서 버튼에 props(width)를 넘겨주던 구조에서 @media를 이용하여 width를 동적으로 설정하도록 조정했습니다.
> 로그인 페이지 view 리팩토링

- server/src/db/models/index.js
> hotfix - models 경로 수정

- client/src/components/common/modals/form-modal-account/FormModalCreateAccount.tsx
- client/src/components/common/modals/form-modal-account/FormModalUpdateAccount.tsx
- client/src/components/common/modals/form-modal-category/FormModalCreateCategory.tsx
- client/src/components/common/modals/form-modal-category/FormModalUpdateCategory.tsx
- client/src/components/common/modals/form-modal-header/FormModalHeader.tsx
- client/src/components/common/modals/form-modal-header/SMSIcon.tsx
- client/src/components/common/modals/form-modal-transaction/FormModalCreateTransaction.tsx
- client/src/constants/formModal.ts
close #232 [가계부 내역 페이지] sms 아이콘 생성 
- sms icon 생성
- question icon 생성
- question hover 하면 sms 기능에대한 설명 출력
- 상수파일에 있는 변수들 네이밍 컨벤션 통일
> sms, question 아이콘 생성

- client/src/components/common/modals/form-modal-category/FormModalCreateCategory.tsx
- 민수님의 리뷰를 반영하여 조건문을 간결하게 수정하였습니다.
중복 검사 시 경우에 따라 반환하는 곳이 복잡한데 이 부분은 추후 함수화하겠습니다..
> 코드 리뷰 반영한 조건문 리팩토링

- server/src/db/models/accountbook.js
- server/src/db/seeders/2020120220-accountbook.js
- 더이상 필요없어진 속성들을 제거하고 그에 맞춰 더미데이터 내용을 변경했습니다.
- production, test 데이터베이스에 모두 새로운 데이터베이스 스키마를 반영했고, 더미데이터를 넣어놨습니다.
- erd 문서 수정했습니다.
> 달력 기능에 필요했던 속성들 제거

- client/src/components/common/transactions/transaction-item/TransactionItem.tsx
close #309 카테고리 컴포넌트 버그 수정
- 이벤트 캡쳐링을 사용하여 내역아이템을 눌렀을 때 카테고리 컴포넌트에 종속된 이벤트(openUpdateCategoryForm)가 실행되는 버그를 수정하였습니다.
> 카테고리 컴포넌트 버그 수정

- client/src/pages/infinite-scroll-test-page/InfiniteScrollTestPage.tsx
- client/src/pages/infinite-scroll-test-page/InfiniteScrollTestView.tsx
close #314 formFilterStore => filterFormStore 이름 변경되어 발생한 오류 해결
> formFilterStore를 filterFormStore로 변경

- server/src/api/controllers/accountbook.js
- server/src/services/accountbook.js
> merge 중 충돌 잘못 해결한 부분 수정

- client/src/pages/settings-accountbook-page/SettingsAccountbookPage.tsx
- client/src/pages/transaction-page/TransactionView.tsx
close #367 [가계부 내역 페이지] TopButton 오류 해결
> Top 버튼 오류 해결

- server/src/services/oauth.js
데모용 가계부의 색깔이 너무 투박해서 좀 더 예쁜 색으로 수정하였습니다.
> 데모용 가계부 색 수정
